### ISSUE TITLE
V1 Roadmap

### ISSUE THREAD

**Issue by themisir** [TheMisir/form-validator#1]
This issue contains tasks required to be accomplished before v1.0 release.

## General

- [x] Listing
- [ ] Write tests for each validation
  - [x] Length
  - [x] Email
  - [x] Phone
  - [x] IP
  - [x] URL
  - [ ] Text comparison
  - [ ] Password validation
- [x] Consider about class naming
- [x] Simple locale management

## Validators

- [x] Length (min, max)
- [x] Email
- [x] Phone
- [x] IP (v4, v6)
- [x] URL
- [ ] Text comparison (eg.: password and password repeat should be same)
- [ ] Password validation
  - [ ] Min. length
  - [ ] Symbols
  - [ ] Lowercase letter
  - [ ] Uppercase letter
  - [ ] Number
- [ ] ???

## Languages

- [x] English
- [x] Azerbaijani
- [x] Turkish
- [ ] Russian
- [x] Chinese
- [ ] ???

**Comment by masseelch** [comment]
I added a notBlank validator, which just is a required validator with an extra check against the empty string.
